//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        public int attendence_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
