//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int notification_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string message_info { get; set; }
        public Nullable<int> log_id { get; set; }
        public Nullable<int> parent_id { get; set; }
    
        public virtual ACCESS_LOG ACCESS_LOG { get; set; }
        public virtual PARENT PARENT { get; set; }
    }
}
