//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.ACCESS_LOG = new HashSet<ACCESS_LOG>();
            this.ATTENDANCE = new HashSet<ATTENDANCE>();
            this.CANTEEN = new HashSet<CANTEEN>();
            this.PARENT = new HashSet<PARENT>();
        }
    
        public int student_id { get; set; }
        public string student_firstname { get; set; }
        public string student_lastname { get; set; }
        public Nullable<System.DateTime> student_birthdate { get; set; }
        public string student_gender { get; set; }
        public byte[] student_image { get; set; }
        public string student_adress { get; set; }
        public Nullable<decimal> student_balance { get; set; }
        public Nullable<int> district_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public int student_schoolNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESS_LOG> ACCESS_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE> ATTENDANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANTEEN> CANTEEN { get; set; }
        public virtual CLASS CLASS { get; set; }
        public virtual DISTRICT DISTRICT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARENT> PARENT { get; set; }
        public virtual PARENT PARENT1 { get; set; }
    }
}
