//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_CLASS
    {
        public int teacher_class_id { get; set; }
        public int teacher_id { get; set; }
        public int class_id { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
